use_frameworks!

platform :ios, '9.0'

target 'LancooPhotoBrowser_Example' do
  pod 'LancooPhotoBrowser', :path => '../'

  target 'LancooPhotoBrowser_Tests' do
    inherit! :search_paths

    
  end
end
